---
- hosts: icinga-coreserver
  roles:
    - icinga-core
    - icinga-nrpe-plugin
    - icinga-nrpe-server

- hosts: icinga-gearman
  roles:
    - gearman
    - icinga-nrpe-server
    - icinga-nrpe-server

- hosts: icinga-satellite
  roles:
    - icinga-satellite
    - icinga-nrpe-plugin
    - icinga-nrpe-server

- hosts: gateways
  roles:
    - icinga-nrpe-server

