---
- name: Install NRPE-Server
  apt: pkg=nagios-nrpe-server state=installed update_cache=true

- name: Configure NRPE-Server
  template: "src=nrpe_local.cfg.j2 dest='/etc/nagios/nrpe_local.cfg' owner=root group=root"
  notify:
    - Reload nagios-nrpe-server
